module.exports = `
  type Restaurant {
      _id: ID!
      name: String
      email: String
      phone: String
      menus: [Menu]
  }

  extend type Query {
      restaurants: [Restaurant]
      restaurant(_id: ID!): Restaurant
      restaurantsByEmail(email: String!): [Restaurant]
      restaurantsByName(name: String!): [Restaurant]
      restaurantsByPhone(phone: String!): [Restaurant]
  }

  extend type Mutation {
    createRestaurant(
      name: String!
      email: String
      phone: String
      menus: [String]
    ): Restaurant
    editRestaurant(
      _id: ID!
      name: String
      email: String
      phone: String
    ): Restaurant
    deleteRestaurant(
      _id: ID!
    ): DeleteResponse
    addMenuToRestaurant(
      restaurantId: ID!
      menuId: ID!
    ): Boolean
    removeMenuFromRestaurant(
      restaurantId: ID!,
      menuId: ID!
    ): Boolean
  }
`