module.exports = `
  type Category {
    _id: ID!
    name: String!
    images: [String]
    description: String
    price: String
    notes: [Note]
    items: [Item]
  }

  input CategoryInput {
    name: String!
    images: [String]
    description: String
    price: String
    notes: [ID]
    items: [ID]
  }

  extend type Query {
    categories: [Category]
    category(_id: ID): Category
    categoryByName(name: String): Category
  }

  extend type Mutation {
    createCategory(category: CategoryInput!): Category
    editCategory(category: CategoryInput!, _id: ID!): Category
    deleteCategory(_id: ID!): DeleteResponse
    addNoteToCategory(noteId: ID!, categoryId: ID!): Boolean
    removeNoteFromCategory(noteId: ID!, categoryId: ID!): Boolean
    addItemToCategory(itemId: ID!, categoryId: ID!): Boolean
    removeItemFromCategory(itemId: ID!, categoryId: ID!): Boolean
  }
`