module.exports = `
  type Item {
      _id: ID!
      name: String!
      description: String
      price: String
      images: [String]
      notes: [Note]
      tags: [Tag]
      isAvailable: Boolean
  }

  extend type Query {
      items: [Item]
      item(_id: ID): Item
      itemByName(name: String): Item
  }

  extend type Mutation {
    createItem(name: String!, description: String, price: String, images: String, notes: [ID], tags: [ID]): Item
    editItem(_id: ID!, name: String, description: String, price: String, images: String): Item
    deleteItem(_id: ID!): DeleteResponse
    addNoteToItem(noteId: ID!, itemId: ID!): Boolean
    removeNoteFromItem(noteId: ID!, itemId: ID!): Boolean
    addTagToItem(tagId: ID!, itemId: ID!): Boolean
    removeTagFromItem(tagId: ID!, itemId: ID!): Boolean
  }
`