module.exports = `
  type Note {
      _id: ID!
      description: String
  }

  extend type Query {
      allNotes: [Note]
      note(_id: ID): Note
  }

  extend type Mutation {
    createNote(description: String!): Note
    editNote(_id: ID!, description: String): Note
    deleteNote(_id: ID!): Note
  }
`