module.exports = `
  type User {
    _id: ID!
    username: String!
    password: String!
    displayName: String
    email: String
    teams: [Team]
    isAdmin: Boolean
  }

  type Auth {
    user: User
    token: String
  }

  extend type Query {
    allUsers: [User]
    user(username: String!): User
    me: User
  }

  extend type Mutation {
    createUser(
      username: String!
      password: String!
      displayName: String
      email: String!
      isAdmin: Boolean
    ): Auth
    updateUser(
      username: String
      displayName: String
      email: String
    ): User
    editUser(
      _id: ID!
      username: String
      password: String
      displayName: String
      email: String
      isAdmin: Boolean): User
    login(username: String!, password: String): Auth
    changePassword(oldPass: String!, newPass: String!): Boolean
  }
`