module.exports = `
  type Role {
      _id: ID!
      user: User
      team: Team
      role: RoleType 
  }

  enum RoleType {
    OWNER,
    EDITOR,
    VIEWER
  }

  extend type Query {
    allRoles: [Role]
    role(_id: ID!): Role
    rolesForUser(userId: String!): [Role]
    rolesForTeam(teamId: String!): [Role]
    rolesAsOwner: [Role]
    rolesAsEditor: [Role]
    rolesAsViewer: [Role]
  }

  extend type Mutation {
    createRole(
      user: String!
      team: String!
      role: RoleType
    ): Role
    deleteRole(
      _id: ID!
    ): DeleteResponse
    changeRole(
      roleId: ID!
      newRole: RoleType!
    ): Role
  }
`