module.exports = `
  type Availability {
    _id: ID!
    item: ID!
    startDate: Date
    endDate: Date
    startTime: String
    endTime: String
    type: String
    isAvailable: Boolean
  }

  extend type Query {
    availability(_id: ID): Availability
    availabilitiesForItem(itemId: ID!): [Availability]
  }

  extend type Mutation {
    createAvailability(
      item: ID!,
      startDate: Date,
      endDate: Date,
      startTime: String,
      endTime: String,
      type: String,
      isAvailable: Boolean
    ): Availability
    setAvailabilityDates(_id: ID!, startDate: Date, endDate: Date): Availability
    setAvailabilityTimes(_id: ID!, startTime: String, endTime: String): Availability
    setAvailabilityOverride(_id: ID!, isAvailable: Boolean!): Availability
    deleteAvailability(_id: ID!): DeleteResponse
  }
`