module.exports = `
  type Menu {
    _id: ID!
    title: String!
    description: String
    logo: String
    bgImage: String
    categories: [Category]
    teamId: ID!
    domains: [String]
  }

  input MenuInput {
    title: String!
    description: String
    logo: String
    bgImage: String
    categories: [CategoryInput]
    teamId: ID!
  }  

  extend type Query {
    allMenus: [Menu]
    menu(_id: ID!): Menu
    menuByTitle(title: String): Menu
    menuByDomain(domain: String): Menu
  }

  extend type Mutation {
    createMenu(menu: MenuInput!): Menu
    updateMenu(menu: MenuInput!, _id: ID!): Menu
    deleteMenu(_id: ID!): DeleteResponse
    addCategoryToMenu(categoryId: ID!, menuId: ID!): Boolean
    removeCategoryFromMenu(categoryId: ID!, menuId: ID!): Boolean
    addDomainToMenu(_id: ID!, domain: String!): Boolean
    removeDomainFromMenu(_id: ID!, domain: String!): Boolean
  }
`