module.exports = `
  type Menu {
      _id: ID!
      title: String!
      logo: String
      bgImage: String
      categories: [Category]
  }

  extend type Query {
      menus: [Menu]
      menu(_id: ID): Menu
      menuByTitle(title: String): Menu
  }

  extend type Mutation {
    createMenu(title: String!, logo: String, bgImage: String, categories: [ID]): Menu
    editMenu(_id: ID!, title: String, logo: String, bgImage: String): Menu
    deleteMenu(_id: ID!): DeleteResponse
    addCategoryToMenu(categoryId: ID!, menuId: ID!): Boolean
    removeCategoryFromMenu(categoryId: ID!, menuId: ID!): Boolean
  }
`