module.exports = `
  type Membership {
      _id: ID!
      team: Team
      type: MembershipType 
  }

  enum MembershipType {
    FREE,
    STARTER,
    MONTHLY
  }

  extend type Query {
    memberships: [Membership]
    membership(_id: ID!): Membership
    membershipsForTeam(teamId: String!): [Membership]
  }

  extend type Mutation {
    createMembership(
      team: String!
      type: MembershipType
    ): Membership
    deleteMembership(
      _id: ID!
    ): DeleteResponse
    changeMembershipType(
      membershipId: ID!
      newType: MembershipType!
    ): Membership
  }
`