module.exports = `
  type Membership {
      _id: ID!
      team: Team
      type: MembershipType
      status: MembershipStatus
      stripeSubId: String
  }

  enum MembershipType {
    FREE,
    STARTER,
    MONTHLY
  }

  enum MembershipStatus {
    INITIALIZED,
    PENDING,
    ACTIVE,
    FAILED,
    CANCELLED
  }

  extend type Query {
    allMemberships: [Membership]
    membership(_id: ID!): Membership
    membershipsForTeam(teamId: String!): [Membership]
  }

  extend type Mutation {
    createMembership(
      team: String!
      type: MembershipType
    ): Membership
    deleteMembership(
      _id: ID!
    ): DeleteResponse
    changeMembershipType(
      membershipId: ID!
      newType: MembershipType!
    ): Membership
  }
`