module.exports = `
  type Team {
      _id: ID!
      name: String
      owner: User
      users: [User]
      restaurants: [Restaurant]
  }

  extend type Query {
      teams: [Team]
      team(_id: ID!): Team
      teamsForUser(userId: String!): [Team]
      teamsForOwner(userId: String!): [Team]
      teamsByName(name: String!): [Team]
      teamsForRestaurant(restaurantId: String!): [Team]
  }

  extend type Mutation {
    createTeam(
      name: String
      owner: String!
      users: [String]
      restaurants: [String]
    ): Team
    editTeam(
      _id: ID!
      name: String
    ): Team
    deleteTeam(
      _id: ID!
    ): DeleteResponse
    addRestaurantToTeam(
      teamId: ID!
      restaurantId: ID!
    ): Boolean
    removeRestaurantFromTeam(
      teamId: ID!
      restaurantId: ID!,
    ): Boolean
    addUserToTeam(
      teamId: ID!
      userId: ID!
    ): Boolean
    removeUserFromTeam(
      teamId: ID!
      userId: ID!,
    ): Boolean
    changeTeamOwner(
      teamId: ID!
      userId: ID!
    ): Team
  }
`