module.exports = `
  type Discount {
    _id: ID!
    item: ID!
    startDate: Date
    endDate: Date
    startTime: String
    endTime: String
    priceFixedAdjust: Float
    pricePercentAdjust: Float
    priceType: String
    durationType: String
  }

  extend type Query {
    discount(_id: ID): Discount
    discountsForItem(itemId: ID!): [Discount]
  }

  extend type Mutation {
    createDiscount(
      item: ID!,
      startDate: Date,
      endDate: Date,
      startTime: String,
      endTime: String,
      priceFixedAdjust: Float,
      pricePercentAdjust: Float,
      priceType: String,
      durationType: String,
    ): Discount
    setDiscountDates(_id: ID!, startDate: Date, endDate: Date): Discount
    setDiscountTimes(_id: ID!, startTime: String, endTime: String): Discount
    setDiscountFixedPrice(_id: ID!, priceFixedAdjust: Float!): Discount
    setDiscountPercentPrice(_id: ID!, pricePercentAdjust: Float!): Discount
    deleteDiscount(_id: ID!): DeleteResponse
  }
`